# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Lambda Layer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # For more info: https://github.com/aws-actions/configure-aws-credentials
  deploy:
    name: Upload zip to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Zip it all up and upload to S3
        env:
          release_id: ${GITHUB_REPOSITORY}-${GITHUB_RUN_ID}
          release: ${release_id}.zip
        run: |
          mkdir python
          pip install wheel
          pip install -r requirements.txt -t python
          pip install -e python
          echo building release $release
          zip -r $release python
          aws s3 cp $release  s3://net.dilex.github

